apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fizzbuzz
    hasuraService: custom
  name: fizzbuzz 
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: fizzbuzz 
  type: LoadBalancer
status:
  loadBalancer: {}
